############
# Аннотации
############

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Doctrine\Common\Annotations\AnnotationReader: '@annotations.reader'
  Doctrine\Common\Annotations\Reader: '@annotations.reader'
  annotation_reader: '@Doctrine\Common\Annotations\AnnotationReader'

  annotations.dummy_registry:
    class: Doctrine\Common\Annotations\AnnotationRegistry
    calls:
      - registerUniqueLoader: ['class_exists']

  annotations.reader:
    class: Doctrine\Common\Annotations\AnnotationReader
    calls:
      - addGlobalIgnoredName: ['required', '@annotations.dummy_registry']

  annotations.filesystem_cache_adapter:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      - 'annotations'
      - '%annotations_ttl_cache%'
      - '%file_cache_dir%'

  annotations.filesystem_cache:
    class: Symfony\Component\Cache\DoctrineProvider
    arguments:
      - '@annotations.filesystem_cache_adapter'

  annotations.cached_reader:
    class: Doctrine\Common\Annotations\CachedReader
    arguments:
      - '@annotations.reader'
      - '@annotations.filesystem_cache'
      - '%kernel.debug%'

  annotations.php_array_adapter_factory:
    class: Symfony\Component\Cache\Adapter\PhpArrayAdapter
    factory: ['Symfony\Component\Cache\Adapter\PhpArrayAdapter', 'create']
    arguments:
      - '%kernel.cache_dir%/annotations.php'
      - '@cache.annotations'

  annotations.cache:
    class: Symfony\Component\Cache\DoctrineProvider
    arguments:
      - '@annotations.php_array_adapter_factory'
