services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ##############################
  # Стандартные команды Symfony
  ##############################

  console.command.event_dispatcher_debug:
    class: Symfony\Bundle\FrameworkBundle\Command\EventDispatcherDebugCommand
    arguments: ['@event_dispatcher']
    tags:
      - { name: console.command, comand: debug:event-dispatcher }

  console.command.container_debug:
    class: Prokl\CustomFrameworkExtensionsBundle\Command\Fork\ContainerDebugCommand
    calls:
      - setContainer: ['@service_container']
    tags:
      - { name: console.command, comand: debug:container }

  console.command.debug_autowiring:
    class: Prokl\CustomFrameworkExtensionsBundle\Command\Fork\DebugAutowiringCommand
    calls:
      - setContainer: ['@service_container']
    arguments: [~, ~]
    tags:
      - { name: console.command, comand: debug:autowiring }

  console.command.dump_reference:
    class: Prokl\CustomFrameworkExtensionsBundle\Command\Fork\ConfigDumpReferenceCommand
    calls:
      - setContainer: ['@service_container']
    tags:
      - { name: console.command, comand: config:dump-reference }

  ####################
  # Кастомные команды
  ####################

  # Создать тест.
  Prokl\CustomFrameworkExtensionsBundle\Command\CreateTest\CreateTest:
    tags:
      - { name: console.command, command: make:test }