###########
# Секреты
###########

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  secrets.vault:
    class: Symfony\Bundle\FrameworkBundle\Secrets\SodiumVault
    arguments:
      - ''
      - '@secrets.decryption_key'
    tags:
      - { name: container.env_var_loader}

  secrets.decryption_key:
    autowire: false
    autoconfigure: false
    public: true
    parent: 'container.env'
    arguments: ['']

  secrets.local_vault:
    class: Symfony\Bundle\FrameworkBundle\Secrets\DotenvVault
    arguments: ['']
